/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TestBridgeMessageInterface extends ethers.utils.Interface {
  functions: {
    "testFormatMessage(bytes29,bytes29)": FunctionFragment;
    "testIsValidAction(bytes29)": FunctionFragment;
    "testIsValidMessageLength(bytes29)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "testFormatMessage",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testIsValidAction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testIsValidMessageLength",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "testFormatMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testIsValidAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testIsValidMessageLength",
    data: BytesLike
  ): Result;

  events: {};
}

export class TestBridgeMessage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TestBridgeMessageInterface;

  functions: {
    testFormatMessage(
      _tokenId: BytesLike,
      _action: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    testIsValidAction(
      _action: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    testIsValidMessageLength(
      _view: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  testFormatMessage(
    _tokenId: BytesLike,
    _action: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  testIsValidAction(
    _action: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  testIsValidMessageLength(
    _view: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    testFormatMessage(
      _tokenId: BytesLike,
      _action: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    testIsValidAction(
      _action: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    testIsValidMessageLength(
      _view: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    testFormatMessage(
      _tokenId: BytesLike,
      _action: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testIsValidAction(
      _action: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testIsValidMessageLength(
      _view: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    testFormatMessage(
      _tokenId: BytesLike,
      _action: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testIsValidAction(
      _action: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testIsValidMessageLength(
      _view: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
