image:
  repository: gcr.io/clabs-optics/optics-agent
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podCommonLabels: {}

storage:
  storageClass: "standard"
  accessModes: ReadWriteOnce

# -- Optics Overrides
# By Default, Optics Agents load the config baked into the Docker Image
# Pass values here in order to override the values in the config
# Note: For successful operation, one _must_ pass signer keys as
#       they are not baked into the image for security reasons.
optics:
  # Sets the config folder to use
  runEnv: "default"
  # Sets the base config to be used (switch between Homes)
  baseConfig: "base.json"
  # Set the DB location to be the volume
  dbPath: /usr/share/optics
  rustBacktrace: full
  tracing:
    # Set the log formatting
    format: json
    # Set the log level
    level: info
    uri: ""
  metrics: 
    port: 9090
  homeChain:
    name: "kovan"
    # -- The contract address for the home contract
    address: # "0x0C473afC0cabd469751CBE3Ac08aBac3e40bF586"
    # -- The hard-coded domain corresponding to this blockchain
    domain: # 1000
    # -- RPC Style
    rpcStyle: # "ethereum"
    connectionType: # "http"
    # -- Connection string pointing to an RPC endpoint for the home chain
    connectionUrl: # "https://kovan.infura.io/v3/<KEY>"
  aws:
    # accessKeyId: ""
    # secretAccessKey: ""

  # -- Replica chain overrides, a sequence
  replicaChains:
    - name: "alfajores"
      # -- The contract address for the replica contract
      address: # "0x0C473afC0cabd469751CBE3Ac08aBac3e40bF586"
      domain: # 1000
      rpcStyle: # "ethereum"
      connectionType: # "http"
      # -- Connection string pointing to an RPC endpoint for the replica chain
      connectionUrl: # "https://alfajores-forno.celo-testnet.org"

  # Optics Agent Roles
  # Individually Switchable via <role>.enabled
  updater:
    enabled: false
    podAnnotations: {}
    podLabels: {}
    storage:
      size: 10Gi
      snapshot:
        enabled: false
        name: ""
    resources: {}
    # -- Transaction Signing keys for home and replica(s)
    transactionSigners:
      - name: "kovan"
        hexKey: ""
        aws:
          keyId: ""
          region: ""
      - name: "alfajores"
        hexKey: ""
        aws:
          keyId: ""
          region: ""
    # -- Specialized key used by updater and watcher used to sign attestations, separate from updater.transactionSigners
    attestationSigner:
      hexKey: ""
      aws:
        keyId: ""
        region: ""
    # -- How long to wait between checking for updates
    pollingInterval: # 5
    updatePause: # 15

  relayer:
    enabled: false
    podAnnotations: {}
    podLabels: {}
    storage:
      size: 10Gi
      snapshot:
        enabled: false
        name: ""
    resources: {}
    transactionSigners:
      - name: "kovan"
        hexKey: ""
        aws:
          keyId: ""
          region: ""
      - name: "alfajores"
        hexKey: ""
        aws:
          keyId: ""
          region: ""
    pollingInterval: # 10

  processor:
    enabled: false
    podAnnotations: {}
    podLabels: {}
    storage:
      size: 10Gi
      snapshot:
        enabled: false
        name: ""
    resources: {}
    transactionSigners:
      - name: "kovan"
        hexKey: ""
        aws:
          keyId: ""
          region: ""
      - name: "alfajores"
        hexKey: ""
        aws:
          keyId: ""
          region: ""
    pollingInterval: # 10

  kathy:
    enabled: false
    podAnnotations: {}
    podLabels: {}
    storage:
      size: 10Gi
      snapshot:
        enabled: false
        name: ""
    resources: {}
    transactionSigners:
      - name: "kovan"
        hexKey: ""
        aws:
          keyId: ""
          region: ""
      - name: "alfajores"
        hexKey: ""
        aws:
          keyId: ""
          region: ""
    # Polling Interval Override
    messageInterval: # 100
    # -- Configuration for Kathy's message generation code
    chatGenConfig:
      destination: # 2000
      message: # "hello are you listening?"
      recipient: # "recipient"
      type: # "static"

podSecurityContext:
  fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
