message-interval = 100
chat-gen-config = { type = "static", destination = 1, recipient = "recipient", message = "static message" }

[home]
name = "celo"
domain = 52752
address = "0x0000000000000000000000000000000000000000"
rpc-style = "Ethereum"
    [home.config]
    signer = "380eb0f3d505f087e438eca80bc4df9a7faa24f868e69fc0440261a0fc0567dc"
    connection = { type = "http", url = "http://localhost:8545" }

[[replicas]]
# empty vector.
# no replicas needed for kathy