[package]
name = "relayer"
version = "0.1.0"
authors = ["ltchang <ltchang@stanford.edu>"]
edition = "2018"

[dependencies]
tokio = { version = "1.0.1", features = ["rt", "macros"] }
config = "0.10"
serde = "1.0.120"
serde_json = { version = "1.0.61", default-features = false }
log = "0.4.13"
ethers = { git = "https://github.com/gakonst/ethers-rs", features = ["abigen"] }
thiserror = { version = "1.0.22", default-features = false }
async-trait = { version = "0.1.42", default-features = false }
futures-util = "0.3.12"
color-eyre = "0.5.0"
tracing = "0.1.22"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.15"

optics-core = { path = "../optics-core" }
optics-base = { path = "../optics-base" }

[dev-dependencies]
tokio-test = "0.4.0"
optics-test = { path = "../optics-test" }
