[home]
slip44 = 52752
address = "0x0000000000000000000000000000000000000000"
rpc-style = "ethereum"
    [home.config]
    signer = "380eb0f3d505f087e438eca80bc4df9a7faa24f868e69fc0440261a0fc0567dc"
    connection = { type = "http", url = "http://localhost:8545" }

[replicas]
    [replicas.EthereumMainnet]
    slip44 = 60
    address = "0x0000000000000000000000000000000000000000"
    rpc-style = "ethereum"
        [replicas.EthereumMainnet.config]
        connection = { type = "ws", url = "ws://localhost:8545"}

    [replicas.EthereumClassic]
    slip44 = 61
    address = "0x0000000000000000000000000000000000000000"
    rpc-style = "ethereum"
        [replicas.EthereumClassic.config]
        connection = { type = "ws", url = "ws://localhost:8545"}

[tracing]
level = "debug"
style = "pretty"