updater = {type = "hex-key", key = "380eb0f3d505f087e438eca80bc4df9a7faa24f868e69fc0440261a0fc0567dc"}

db_path = "db_path"
polling_interval = 100
update_pause = 100

[home]
name = "ethereum"
domain = 52752
address = "0x0000000000000000000000000000000000000000"
rpc-style = "ethereum"
    [home.config]
    signer = {type = "hex-key", key = "380eb0f3d505f087e438eca80bc4df9a7faa24f868e69fc0440261a0fc0567dc"}
    connection = { type = "http", url = "http://localhost:8545" }

[[replicas]]
# empty table.
# no replicas needed for updater