polling_interval = 100
db_path = "db_path"

[tracing]
level = "debug"
style = "pretty"

# ChainSetup
[home]
name = "celo"
domain = 52752
address = "0x0000000000000000000000000000000000000000"
rpc-style = "ethereum" # ChainConf (flattened into ChainSetup)
    [home.config]
    # Missing signer. Will use EthereumSigner::default()
    connection = { type = "http", url = "http://localhost:8545" }

# Entry in Vec<ChainSetup>
[[replicas]]
name = "ethereum"
domain = 60
address = "0x0000000000000000000000000000000000000000"
rpc-style = "ethereum"
    [replicas.config]
     signer =  {type = "hex-key", key = "380eb0f3d505f087e438eca80bc4df9a7faa24f868e69fc0440261a0fc0567dc"}
    connection = { type = "ws", url = "ws://localhost:8545"}


# Entry in Vec<ChainSetup>
[[replicas]]
name = "eth-classic"
domain = 61
address = "0x0000000000000000000000000000000000000000"
rpc-style = "ethereum"
    [replicas.config]
    connection = { type = "ws", url = "ws://localhost:8545"}
