name: Typechain-generation

on:
  pull_request_review:
    types: [submitted]
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  typechain-generation:
    # if: github.event.review.state == 'approved'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./solidity/optics-core

    steps:
      - uses: actions/checkout@v2

      # TODO: modulize typechain gen script?
      - name: Install
        run: |
          npm i
          npm run compile
          cd ../.. 
          git add typescript/typechain
          git add solidity/optics-core/contracts
          git add solidity/optics-core/libs
          git add solidity/optics-core/interfaces
          git commit -m "Typechain Generation"
